name: Simple Agent

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  respond:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Test') || contains(github.event.comment.body, 'claude')

    steps:
    - uses: actions/checkout@v4

    - name: Test Response
      run: echo "Agent is working!"

    - name: Comment on Issue
      uses: actions/github-script@v6
      with:
        script: |
          const issueNumber = context.issue.number;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: '🤖 **Simple Agent Response**\n\nThe agent system is working! Current best performance: 43.12 pts/day\n\nTarget: 50+ pts/day (16% gap remaining)'
          });